### ISSUE TITLE
Deleting and renaming resources

### ISSUE THREAD

**Issue by byewokko** [TeskaLabs/seacat-admin-webui#1]
Resource detail
- [ ] Deleting a resource
- [ ] Undeleting a resource
- [ ] Renaming a resource

Resource list
- [ ] Option to show deleted resources

For API reference, see https://github.com/TeskaLabs/seacat-auth/pull/113

**Comment by petrKavulok** [comment]
https://github.com/TeskaLabs/seacat-admin-webui/pull/19
